<?php

// Reads a list of urls, each of which describes a GEF paper.
// That list is generated by getListOfGEFpages.php.
// Scerapes each of those pages, building JSON


ini_set('display_errors', 'On');
error_reporting(E_ALL);

// list of GEF publications, generated by getListOfGEFpages.php..php
// Filename is GEFlinks.txt

include "simple_html_dom.php";

//DEBUG
$listOfUrls="GEFlinks.txt"; 
// where in the list you want to start and end
$start = 0;



// get the file of  urls
$pubsliststring = file_get_contents($listOfUrls);
// turn the list of urls into an array
$pubsUrls = explode(PHP_EOL,$pubsliststring);
$end = count($pubsUrls);

print "<p>Scraping " . $end . ".</p>";

// go through each page

for ($i=$start; $i < $end; $i++){ 

	$file = $pubsUrls[$i];
	print "<br>--------Filename: " . $file;
	$html = file_get_html($file);
			

	//  ------- AUTHOR
	$meta = strpos($html, "Author:"); 
	if ($meta !== false ){
		$p2 = strpos($html, "</div>", $meta);
		$author = substr($html, $meta + 8, $p2 - ($meta + 8));
	}
	else {
		$author = "";
	}
	$author = strip_tags($author);
	print "<br>Author: " . $author . ".";

	//  ------- TITLE
	$meta = $html->find('[class=breadcrumb]'); 
	if (isset($meta[0])){
		$title = $meta[0]->innertext;
		// remove preface
		$p = strpos($title, "»");
		if ($p > -1){
			$title = substr($title, $p + 2);
		}
	}
	else{
		$title="";
	}
	print "<br> TITLE: " . $title;
	
	// ------- PAGES
	$meta = strpos($html, "Pages:"); 
	if ($meta !== false ){
		$p2 = strpos($html, "</div>", $meta);
		$pages = substr($html, $meta + 7, $p2 - ($meta + 8));
	}
	else {
		$pages = "";
	}
	$pages = strip_tags($pages);
	print "<br>PAges: " . $pages . ".";
	
	// ------- ISBN
	$meta = strpos($html, "ISBN:"); 
	if ($meta !== false ){
		$p2 = strpos($html, "</div>", $meta);
		$isbn = substr($html, $meta + 6, $p2 - ($meta));
		//print "<br>ISBN debug: meta =$meta len=" . ($p2 - $meta);
	}
	else {
		$isbn = "";
	}
	//$isbn = strip_tags($isbn);
	print "<br>isbn: " . $isbn . ".";
	
	//  ------- TAGS
	$tags = array ();
	$meta = $html->find('a'); // get all links
	// look for rel=tag
	foreach ($meta as $a){
		if ($a->rel == "tag"){
			$tag = $a->innertext;
			$tags[] = $tag;
			print "<br>tag: " . $tag;
		}
	}
	
	// ------- DESCRIPTION
	$meta = $html->find('[class=textcontent]'); 
	// desc is first <p> of textcontent
	if (isset($meta[0])){
		$cont = $meta[0]->find('p');
		$desc = $cont[0];
		$desc = strip_tags($desc);
		
	}
	else{
		$desc="";
	}
	print "<br> DESCRIPTION: " . $desc;
	
	// ------- LINK TO PDF
	$meta = $html->find('[class=filefield-file]'); 
	if (isset($meta[0])){
		$pdfobj = $meta[0]->find('a');
		$pdfurl = $pdfobj[0]->href;
		$pdfurl = strip_tags($pdfurl);
		
	}
	else{
		$pdfurl="NO PDF";
	}
	print "<br> pdf: " . $pdfurl;
	
	// build json 
	$talks[] = array(	
				"author"=>$author,
				"title"=>$title,
				"description"=>$desc,
				"tags"=>$tags,
				"transcript"=>$pdfurl,
				"length"=>$pages,
				"isbn"=>$isbn
					);
}

	$json = json_encode($talks);
	$f = fopen("GEFpubs.json","w");
	fwrite($f,$json);
	fclose($f);

?>
